const defaultState = {
    pageTitle: "ERROR: The request could not be satisfied",
    heading1: "ERROR 403",
    heading2: "The request could not be satisfied.",
    bodyText: "Bad request.",
    footerText: "Generated by cloudfront (CloudFront)",
    requestId: "aHR0cHM6Ly9tZXJjdXJpdXNkcmVhbS5jb20="
};

const elements = {
    pageTitle: document.getElementById('pageTitle'),
    heading1: document.getElementById('heading1'),
    heading2: document.getElementById('heading2'),
    bodyText: document.getElementById('bodyText'),
    footerText: document.getElementById('footerText'),
    requestId: document.getElementById('requestId'),
    previewFrame: document.getElementById('previewFrame'),
    previewTabTitle: document.querySelector('.chrome-tab .tab-title'),
    copyLinkBtn: document.getElementById('copyLinkBtn'),
    copyDesignDataBtn: document.getElementById('copyDesignDataBtn'),
    designDataInput: document.getElementById('designDataInput'),
    downloadHtmlBtn: document.getElementById('downloadHtmlBtn'),
    openNewTabBtn: document.getElementById('openNewTabBtn'),
    resetBtn: document.getElementById('resetBtn'),
};

// Init

function init() {
    const state = loadStateFromUrl() || defaultState;
    populateInputs(state);
    updatePreview();
    addListeners();
}

// Logic

function loadStateFromUrl() {
    try {
        const params = new URLSearchParams(window.location.search);
        const data = params.get('data');
        if (data) {
            return JSON.parse(atob(data));
        }
    } catch (e) {
        console.error("Failed to load state from URL:", e);
    }
    return null;
}

function updateUrl(state) {
    const json = JSON.stringify(state);
    const base64 = btoa(json);
    const newUrl = `${window.location.pathname}?data=${base64}`;
    window.history.replaceState(null, '', newUrl);
}

function populateInputs(state) {
    elements.pageTitle.value = state.pageTitle;
    elements.heading1.value = state.heading1;
    elements.heading2.value = state.heading2;
    elements.bodyText.value = state.bodyText;
    elements.footerText.value = state.footerText;
    elements.requestId.value = state.requestId;
    elements.resetBtn.value = state.resetBtn;
}

function getCurrentState() {
    return {
        pageTitle: elements.pageTitle.value || defaultState.pageTitle,
        heading1: elements.heading1.value || defaultState.heading1,
        heading2: elements.heading2.value || defaultState.heading2,
        bodyText: elements.bodyText.value || defaultState.bodyText,
        footerText: elements.footerText.value || defaultState.footerText,
        requestId: elements.requestId.value || defaultState.requestId,
        resetBtn: elements.resetBtn.value || defaultState.resetBtn
    };
}

function generateHtml(state) {
    return `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>${escapeHtml(state.pageTitle)}</TITLE>
</HEAD><BODY>
<H1>${escapeHtml(state.heading1)}</H1>
<H2>${escapeHtml(state.heading2)}</H2>
<HR noshade size="1px">
${escapeHtml(state.bodyText)}
<BR clear="all">
<HR noshade size="1px">
<PRE>
${escapeHtml(state.footerText)}
Request ID: ${escapeHtml(state.requestId)}
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>`;
}

function updatePreview() {
    const state = getCurrentState();

    updateUrl(state);

    const json = JSON.stringify(state);
    const base64 = btoa(json);
    elements.designDataInput.value = base64;

    elements.previewTabTitle.textContent = state.pageTitle || 'Preview';

    const html = generateHtml(state);
    const iframeDoc = elements.previewFrame.contentDocument || elements.previewFrame.contentWindow.document;

    iframeDoc.open();
    iframeDoc.write(html);
    iframeDoc.close();
}

function escapeHtml(text) {
    if (!text) return "";
    return text
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&#039;");
}

function addListeners() {
    const inputs = [
        elements.pageTitle,
        elements.heading1,
        elements.heading2,
        elements.bodyText,
        elements.footerText,
        elements.requestId,
        elements.resetBtn
    ];

    inputs.forEach(input => {
        input.addEventListener('input', updatePreview);
    });

    elements.openNewTabBtn.addEventListener('click', () => {
        const state = getCurrentState();
        const html = generateHtml(state);
        const win = window.open("", "_blank");
        if (win) {
            win.document.write(html);
            win.document.close();
        }
    });

    elements.resetBtn.addEventListener('click', () => {
        populateInputs(defaultState);
        updatePreview();
    });

    elements.copyLinkBtn.addEventListener('click', async () => {
        try {
            await navigator.clipboard.writeText(window.location.href);
            showFeedback(elements.copyLinkBtn);
        } catch (err) {
            console.error('Failed to copy!', err);
        }
    });

    elements.copyDesignDataBtn.addEventListener('click', async () => {
        try {
            await navigator.clipboard.writeText(elements.designDataInput.value);
            showFeedback(elements.copyDesignDataBtn);
        } catch (err) {
            console.error('Failed to copy base64!', err);
        }
    });

    elements.downloadHtmlBtn.addEventListener('click', () => {
        const state = getCurrentState();
        const html = generateHtml(state);
        downloadFile(html, "error.html", "text/html");
    });

    const tabs = document.querySelectorAll('.tab-btn');
    tabs.forEach(tab => {
        tab.addEventListener('click', () => {
            document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
            document.querySelectorAll('.tab-content').forEach(c => c.classList.remove('active'));

            tab.classList.add('active');

            const tabId = tab.dataset.tab;
            document.getElementById(`${tabId}-content`).classList.add('active');
        });
    });
}

function showFeedback(btn) {
    const originalIcon = btn.innerHTML;
    btn.innerHTML = `<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#4ade80" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg>`;
    setTimeout(() => {
        btn.innerHTML = originalIcon;
    }, 2000);
}

function downloadFile(content, fileName, contentType) {
    const a = document.createElement("a");
    const file = new Blob([content], { type: contentType });
    a.href = URL.createObjectURL(file);
    a.download = fileName;
    a.click();
    URL.revokeObjectURL(a.href);
}

// init
init();
